<a href="https://colab.research.google.com/github/abuzar01440/abuzar-portfolio/blob/main/feature_eng_and_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
! pip install optuna

Collecting optuna
  Downloading optuna-4.2.1-py3-none-any.whl.metadata (17 kB)
Collecting alembic>=1.5.0 (from optuna)
  Downloading alembic-1.15.2-py3-none-any.whl.metadata (7.3 kB)
Collecting colorlog (from optuna)
  Downloading colorlog-6.9.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from optuna) (24.2)
Collecting sqlalchemy>=1.4.2 (from optuna)
  Downloading sqlalchemy-2.0.40-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.6 kB)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from optuna) (4.67.1)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.11/dist-packages (from optuna) (6.0.2)
Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic>=1.5.0->optuna) (1.1.3)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.11/dist-packages (from alembic>=1.5.0->optuna) (4.12.2)
Collecting greenlet>=1 (from sqlalchemy>=1.4.2->optuna)
  Downloading greenlet-3.1.1-cp311-cp311-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Downloading optuna-4.2.1-py3-none-any.whl (383 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 383.6/383.6 kB 7.4 MB/s eta 0:00:00
Downloading alembic-1.15.2-py3-none-any.whl (231 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 231.9/231.9 kB 13.7 MB/s eta 0:00:00
Downloading sqlalchemy-2.0.40-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 52.9 MB/s eta 0:00:00
Downloading colorlog-6.9.0-py3-none-any.whl (11 kB)
Downloading greenlet-3.1.1-cp311-cp311-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (602 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 602.4/602.4 kB 31.2 MB/s eta 0:00:00
Installing collected packages: greenlet, colorlog, sqlalchemy, alembic, optuna
Successfully installed alembic-1.15.2 colorlog-6.9.0 greenlet-3.1.1 optuna-4.2.1 sqlalchemy-2.0.40

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,  classification_report, jaccard_score
from sklearn.ensemble import RandomForestClassifier
import optuna
from sklearn.model_selection import cross_val_score

In [4]:
df= pd.read_csv("/content/clean_data_after_eda.csv")
df.head()

,id,channel_sales,cons_12m,cons_gas_12m,cons_last_month,date_activ,date_end,date_modif_prod,date_renewal,forecast_cons_12m,...,var_6m_price_off_peak_var,var_6m_price_peak_var,var_6m_price_mid_peak_var,var_6m_price_off_peak_fix,var_6m_price_peak_fix,var_6m_price_mid_peak_fix,var_6m_price_off_peak,var_6m_price_peak,var_6m_price_mid_peak,churn
0,24011ae4ebbe3035111d65fa7c15bc57,foosdfpfkusacimwkcsosbicdxkicaua,0,54946,0,2013-06-15,2016-06-15,2015-11-01,2015-06-23,0.00,...,0.000131,4.100838e-05,9.084737e-04,2.086294,99.530517,44.235794,2.086425,9.953056e+01,4.423670e+01,1
1,d29c2c54acc38ff3c0614d0a653813dd,MISSING,4660,0,0,2009-08-21,2016-08-30,2009-08-21,2015-08-31,189.95,...,0.000003,1.217891e-03,0.000000e+00,0.009482,0.000000,0.000000,0.009485,1.217891e-03,0.000000e+00,0
2,764c75f661154dac3a6c254cd082ea7d,foosdfpfkusacimwkcsosbicdxkicaua,544,0,0,2010-04-16,2016-04-16,2010-04-16,2015-04-17,47.96,...,0.000004,9.450150e-08,0.000000e+00,0.000000,0.000000,0.000000,0.000004,9.450150e-08,0.000000e+00,0
3,bba03439a292a1e166f80264c16191cb,lmkebamcaaclubfxadlmueccxoimlema,1584,0,0,2010-03-30,2016-03-30,2010-03-30,2015-03-31,240.04,...,0.000003,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000003,0.000000e+00,0.000000e+00,0
4,149d57cf92fc41cf94415803a877cb4b,MISSING,4425,0,526,2010-01-13,2016-03-07,2010-01-13,2015-03-09,445.75,...,0.000011,2.896760e-06,4.860000e-10,0.000000,0.000000,0.000000,0.000011,2.896760e-06,4.860000e-10,0

In [5]:
df.drop(["origin_up","channel_sales"],axis=1,inplace=True)

In [6]:
df.head(2)

,id,cons_12m,cons_gas_12m,cons_last_month,date_activ,date_end,date_modif_prod,date_renewal,forecast_cons_12m,forecast_cons_year,...,var_6m_price_off_peak_var,var_6m_price_peak_var,var_6m_price_mid_peak_var,var_6m_price_off_peak_fix,var_6m_price_peak_fix,var_6m_price_mid_peak_fix,var_6m_price_off_peak,var_6m_price_peak,var_6m_price_mid_peak,churn
0,24011ae4ebbe3035111d65fa7c15bc57,0,54946,0,2013-06-15,2016-06-15,2015-11-01,2015-06-23,0.00,0,...,0.000131,0.000041,0.000908,2.086294,99.530517,44.235794,2.086425,99.530558,44.236702,1
1,d29c2c54acc38ff3c0614d0a653813dd,4660,0,0,2009-08-21,2016-08-30,2009-08-21,2015-08-31,189.95,0,...,0.000003,0.001218,0.000000,0.009482,0.000000,0.000000,0.009485,0.001218,0.000000,0

In [7]:
df["date_activ"] = pd.to_datetime(df["date_activ"], format='%Y-%m-%d')
df["date_end"] = pd.to_datetime(df["date_end"], format='%Y-%m-%d')
df["date_modif_prod"] = pd.to_datetime(df["date_modif_prod"], format='%Y-%m-%d')
df["date_renewal"] = pd.to_datetime(df["date_renewal"], format='%Y-%m-%d')

In [8]:
price_df = pd.read_csv('/content/price_data (1).csv')
price_df["price_date"] = pd.to_datetime(price_df["price_date"], format='%Y-%m-%d')
price_df.head()

,id,price_date,price_off_peak_var,price_peak_var,price_mid_peak_var,price_off_peak_fix,price_peak_fix,price_mid_peak_fix
0,038af19179925da21a25619c5a24b745,2015-01-01,0.151367,0.0,0.0,44.266931,0.0,0.0
1,038af19179925da21a25619c5a24b745,2015-02-01,0.151367,0.0,0.0,44.266931,0.0,0.0
2,038af19179925da21a25619c5a24b745,2015-03-01,0.151367,0.0,0.0,44.266931,0.0,0.0
3,038af19179925da21a25619c5a24b745,2015-04-01,0.149626,0.0,0.0,44.266931,0.0,0.0
4,038af19179925da21a25619c5a24b745,2015-05-01,0.149626,0.0,0.0,44.266931,0.0,0.0

In [9]:
# Group off-peak prices by companies and month
monthly_price_by_id = price_df.groupby(['id', 'price_date']).agg({'price_off_peak_var': 'mean', 'price_off_peak_fix': 'mean'}).reset_index()

# Get january and december prices
jan_prices = monthly_price_by_id.groupby('id').first().reset_index()
dec_prices = monthly_price_by_id.groupby('id').last().reset_index()

# Calculate the difference
diff = pd.merge(dec_prices.rename(columns={'price_off_peak_var': 'dec_1', 'price_off_peak_fix': 'dec_2'}), jan_prices.drop(columns='price_date'), on='id')
diff['offpeak_diff_dec_january_energy'] = diff['dec_1'] - diff['price_off_peak_var']
diff['offpeak_diff_dec_january_power'] = diff['dec_2'] - diff['price_off_peak_fix']
diff = diff[['id', 'offpeak_diff_dec_january_energy','offpeak_diff_dec_january_power']]
diff.head()

,id,offpeak_diff_dec_january_energy,offpeak_diff_dec_january_power
0,0002203ffbb812588b632b9e628cc38d,-0.006192,0.162916
1,0004351ebdd665e6ee664792efc4fd13,-0.004104,0.177779
2,0010bcc39e42b3c2131ed2ce55246e3c,0.050443,1.500000
3,0010ee3855fdea87602a5b7aba8e42de,-0.010018,0.162916
4,00114d74e963e47177db89bc70108537,-0.003994,-0.000001

In [10]:
df_1=diff.join(df.set_index('id'), on='id')

In [11]:

df_1.head()

,id,offpeak_diff_dec_january_energy,offpeak_diff_dec_january_power,cons_12m,cons_gas_12m,cons_last_month,date_activ,date_end,date_modif_prod,date_renewal,...,var_6m_price_off_peak_var,var_6m_price_peak_var,var_6m_price_mid_peak_var,var_6m_price_off_peak_fix,var_6m_price_peak_fix,var_6m_price_mid_peak_fix,var_6m_price_off_peak,var_6m_price_peak,var_6m_price_mid_peak,churn
0,0002203ffbb812588b632b9e628cc38d,-0.006192,0.162916,22034.0,0.0,3084.0,2010-01-19,2016-02-21,2010-01-19,2015-02-25,...,0.000011,0.000003,4.860000e-10,0.0,0.0,0.0,0.000011,0.000003,4.860000e-10,0.0
1,0004351ebdd665e6ee664792efc4fd13,-0.004104,0.177779,4060.0,0.0,0.0,2009-08-06,2016-06-21,2013-06-21,2015-06-23,...,0.000003,0.000000,0.000000e+00,0.0,0.0,0.0,0.000003,0.000000,0.000000e+00,0.0
2,0010bcc39e42b3c2131ed2ce55246e3c,0.050443,1.500000,7440.0,0.0,1062.0,2013-02-25,2016-05-05,2015-05-05,2015-02-26,...,0.000003,0.000000,0.000000e+00,0.0,0.0,0.0,0.000003,0.000000,0.000000e+00,0.0
3,0010ee3855fdea87602a5b7aba8e42de,-0.010018,0.162916,NaN,NaN,NaN,NaT,NaT,NaT,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,00114d74e963e47177db89bc70108537,-0.003994,-0.000001,11272.0,0.0,0.0,2010-03-02,2016-03-02,2010-03-02,2015-03-09,...,0.000003,0.000000,0.000000e+00,0.0,0.0,0.0,0.000003,0.000000,0.000000e+00,0.0

In [12]:
#check null values sum
df_1.isnull().sum()

id                                    0
offpeak_diff_dec_january_energy       0
offpeak_diff_dec_january_power        0
cons_12m                           1490
cons_gas_12m                       1490
cons_last_month                    1490
date_activ                         1490
date_end                           1490
date_modif_prod                    1490
date_renewal                       1490
forecast_cons_12m                  1490
forecast_cons_year                 1490
forecast_discount_energy           1490
forecast_meter_rent_12m            1490
forecast_price_energy_off_peak     1490
forecast_price_energy_peak         1490
forecast_price_pow_off_peak        1490
has_gas                            1490
imp_cons                           1490
margin_gross_pow_ele               1490
margin_net_pow_ele                 1490
nb_prod_act                        1490
net_margin                         1490
num_years_antig                    1490
pow_max                            1490
var_year_price_off_peak_var        1490
var_year_price_peak_var            1490
var_year_price_mid_peak_var        1490
var_year_price_off_peak_fix        1490
var_year_price_peak_fix            1490
var_year_price_mid_peak_fix        1490
var_year_price_off_peak            1490
var_year_price_peak                1490
var_year_price_mid_peak            1490
var_6m_price_off_peak_var          1490
var_6m_price_peak_var              1490
var_6m_price_mid_peak_var          1490
var_6m_price_off_peak_fix          1490
var_6m_price_peak_fix              1490
var_6m_price_mid_peak_fix          1490
var_6m_price_off_peak              1490
var_6m_price_peak                  1490
var_6m_price_mid_peak              1490
churn                              1490
dtype: int64

In [13]:
df_1.dropna(inplace=True)

In [14]:
df_1.drop("id", inplace=True, axis=1)

In [15]:
df_1.isnull().sum()

offpeak_diff_dec_january_energy    0
offpeak_diff_dec_january_power     0
cons_12m                           0
cons_gas_12m                       0
cons_last_month                    0
date_activ                         0
date_end                           0
date_modif_prod                    0
date_renewal                       0
forecast_cons_12m                  0
forecast_cons_year                 0
forecast_discount_energy           0
forecast_meter_rent_12m            0
forecast_price_energy_off_peak     0
forecast_price_energy_peak         0
forecast_price_pow_off_peak        0
has_gas                            0
imp_cons                           0
margin_gross_pow_ele               0
margin_net_pow_ele                 0
nb_prod_act                        0
net_margin                         0
num_years_antig                    0
pow_max                            0
var_year_price_off_peak_var        0
var_year_price_peak_var            0
var_year_price_mid_peak_var        0
var_year_price_off_peak_fix        0
var_year_price_peak_fix            0
var_year_price_mid_peak_fix        0
var_year_price_off_peak            0
var_year_price_peak                0
var_year_price_mid_peak            0
var_6m_price_off_peak_var          0
var_6m_price_peak_var              0
var_6m_price_mid_peak_var          0
var_6m_price_off_peak_fix          0
var_6m_price_peak_fix              0
var_6m_price_mid_peak_fix          0
var_6m_price_off_peak              0
var_6m_price_peak                  0
var_6m_price_mid_peak              0
churn                              0
dtype: int64

In [16]:
df_1.drop(["date_activ",	"date_end",	"date_modif_prod",	"date_renewal"], inplace=True, axis=1)

In [17]:
df_1.head()

,offpeak_diff_dec_january_energy,offpeak_diff_dec_january_power,cons_12m,cons_gas_12m,cons_last_month,forecast_cons_12m,forecast_cons_year,forecast_discount_energy,forecast_meter_rent_12m,forecast_price_energy_off_peak,...,var_6m_price_off_peak_var,var_6m_price_peak_var,var_6m_price_mid_peak_var,var_6m_price_off_peak_fix,var_6m_price_peak_fix,var_6m_price_mid_peak_fix,var_6m_price_off_peak,var_6m_price_peak,var_6m_price_mid_peak,churn
0,-0.006192,0.162916,22034.0,0.0,3084.0,729.06,425.0,0.0,138.95,0.116900,...,0.000011,0.000003,4.860000e-10,0.0,0.0,0.0,0.000011,0.000003,4.860000e-10,0.0
1,-0.004104,0.177779,4060.0,0.0,0.0,597.77,0.0,0.0,6.84,0.142065,...,0.000003,0.000000,0.000000e+00,0.0,0.0,0.0,0.000003,0.000000,0.000000e+00,0.0
2,0.050443,1.500000,7440.0,0.0,1062.0,1311.16,1062.0,30.0,18.37,0.199230,...,0.000003,0.000000,0.000000e+00,0.0,0.0,0.0,0.000003,0.000000,0.000000e+00,0.0
4,-0.003994,-0.000001,11272.0,0.0,0.0,1671.41,0.0,0.0,18.27,0.144149,...,0.000003,0.000000,0.000000e+00,0.0,0.0,0.0,0.000003,0.000000,0.000000e+00,0.0
6,-0.006171,0.000000,267414.0,0.0,19394.0,3077.34,1760.0,0.0,144.86,0.118636,...,0.000011,0.000003,4.860000e-10,0.0,0.0,0.0,0.000011,0.000003,4.860000e-10,0.0

In [18]:
df_1.churn.value_counts()

churn
0.0    13187
1.0     1419
Name: count, dtype: int64

In [19]:
df.has_gas.value_counts()

has_gas
f    11955
t     2651
Name: count, dtype: int64

In [20]:
# convert has_gas into encoder

df_1['has_gas'] = df_1['has_gas'].apply(lambda x: 1 if x == 't' else 0)

In [21]:
df_1.select_dtypes(include='object').columns

Index([], dtype='object')

In [22]:
# convert churn into int
df_1['churn'] = df_1['churn'].astype(int)

In [23]:
df_1.head()

,offpeak_diff_dec_january_energy,offpeak_diff_dec_january_power,cons_12m,cons_gas_12m,cons_last_month,forecast_cons_12m,forecast_cons_year,forecast_discount_energy,forecast_meter_rent_12m,forecast_price_energy_off_peak,...,var_6m_price_off_peak_var,var_6m_price_peak_var,var_6m_price_mid_peak_var,var_6m_price_off_peak_fix,var_6m_price_peak_fix,var_6m_price_mid_peak_fix,var_6m_price_off_peak,var_6m_price_peak,var_6m_price_mid_peak,churn
0,-0.006192,0.162916,22034.0,0.0,3084.0,729.06,425.0,0.0,138.95,0.116900,...,0.000011,0.000003,4.860000e-10,0.0,0.0,0.0,0.000011,0.000003,4.860000e-10,0
1,-0.004104,0.177779,4060.0,0.0,0.0,597.77,0.0,0.0,6.84,0.142065,...,0.000003,0.000000,0.000000e+00,0.0,0.0,0.0,0.000003,0.000000,0.000000e+00,0
2,0.050443,1.500000,7440.0,0.0,1062.0,1311.16,1062.0,30.0,18.37,0.199230,...,0.000003,0.000000,0.000000e+00,0.0,0.0,0.0,0.000003,0.000000,0.000000e+00,0
4,-0.003994,-0.000001,11272.0,0.0,0.0,1671.41,0.0,0.0,18.27,0.144149,...,0.000003,0.000000,0.000000e+00,0.0,0.0,0.0,0.000003,0.000000,0.000000e+00,0
6,-0.006171,0.000000,267414.0,0.0,19394.0,3077.34,1760.0,0.0,144.86,0.118636,...,0.000011,0.000003,4.860000e-10,0.0,0.0,0.0,0.000011,0.000003,4.860000e-10,0

In [24]:
X_train, X_test, y_train, y_test = train_test_split(df_1.drop('churn', axis=1), df_1['churn'], test_size=0.2, random_state=42, stratify=df_1['churn'])

print('X_train shape:', X_train.shape)
print('X_test shape:', X_test.shape)
print('y_train shape:', y_train.shape)
print('y_test shape:', y_test.shape)

X_train shape: (11684, 38)
X_test shape: (2922, 38)
y_train shape: (11684,)
y_test shape: (2922,)

In [25]:
X_train.head()

,offpeak_diff_dec_january_energy,offpeak_diff_dec_january_power,cons_12m,cons_gas_12m,cons_last_month,forecast_cons_12m,forecast_cons_year,forecast_discount_energy,forecast_meter_rent_12m,forecast_price_energy_off_peak,...,var_year_price_mid_peak,var_6m_price_off_peak_var,var_6m_price_peak_var,var_6m_price_mid_peak_var,var_6m_price_off_peak_fix,var_6m_price_peak_fix,var_6m_price_mid_peak_fix,var_6m_price_off_peak,var_6m_price_peak,var_6m_price_mid_peak
7577,-0.009328,0.162916,17750.0,0.0,2915.0,1764.81,2915.0,0.0,146.07,0.115237,...,21.974440,0.000013,2.679260e-06,1.538567e-07,0.007077,0.002548,0.001133,0.007090,2.550800e-03,1.132791e-03
6159,-0.006299,-0.000001,21515.0,0.0,3562.0,550.44,624.0,0.0,105.30,0.142995,...,0.000000,0.000007,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000007,0.000000e+00,0.000000e+00
13298,0.116318,0.162916,139855.0,17967.0,17536.0,6116.50,11474.0,0.0,123.67,0.113323,...,0.001463,0.000011,2.896760e-06,4.860000e-10,0.000000,0.000000,0.000000,0.000011,2.896760e-06,4.860000e-10
14321,-0.004679,0.177779,16341.0,0.0,0.0,2066.10,0.0,0.0,17.49,0.162033,...,0.000000,0.000004,9.450150e-08,0.000000e+00,0.000000,0.000000,0.000000,0.000004,9.450150e-08,0.000000e+00
1605,-0.005360,0.236694,23349.0,10284.0,3661.0,2026.80,3661.0,0.0,131.76,0.102772,...,0.000170,0.000006,1.617204e-06,0.000000e+00,0.000000,0.000000,0.000000,0.000006,1.617204e-06,0.000000e+00

In [26]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 14606 entries, 0 to 16095
Data columns (total 39 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   offpeak_diff_dec_january_energy  14606 non-null  float64
 1   offpeak_diff_dec_january_power   14606 non-null  float64
 2   cons_12m                         14606 non-null  float64
 3   cons_gas_12m                     14606 non-null  float64
 4   cons_last_month                  14606 non-null  float64
 5   forecast_cons_12m                14606 non-null  float64
 6   forecast_cons_year               14606 non-null  float64
 7   forecast_discount_energy         14606 non-null  float64
 8   forecast_meter_rent_12m          14606 non-null  float64
 9   forecast_price_energy_off_peak   14606 non-null  float64
 10  forecast_price_energy_peak       14606 non-null  float64
 11  forecast_price_pow_off_peak      14606 non-null  float64
 12  has_gas                          14606 non-null  int64
 13  imp_cons                         14606 non-null  float64
 14  margin_gross_pow_ele             14606 non-null  float64
 15  margin_net_pow_ele               14606 non-null  float64
 16  nb_prod_act                      14606 non-null  float64
 17  net_margin                       14606 non-null  float64
 18  num_years_antig                  14606 non-null  float64
 19  pow_max                          14606 non-null  float64
 20  var_year_price_off_peak_var      14606 non-null  float64
 21  var_year_price_peak_var          14606 non-null  float64
 22  var_year_price_mid_peak_var      14606 non-null  float64
 23  var_year_price_off_peak_fix      14606 non-null  float64
 24  var_year_price_peak_fix          14606 non-null  float64
 25  var_year_price_mid_peak_fix      14606 non-null  float64
 26  var_year_price_off_peak          14606 non-null  float64
 27  var_year_price_peak              14606 non-null  float64
 28  var_year_price_mid_peak          14606 non-null  float64
 29  var_6m_price_off_peak_var        14606 non-null  float64
 30  var_6m_price_peak_var            14606 non-null  float64
 31  var_6m_price_mid_peak_var        14606 non-null  float64
 32  var_6m_price_off_peak_fix        14606 non-null  float64
 33  var_6m_price_peak_fix            14606 non-null  float64
 34  var_6m_price_mid_peak_fix        14606 non-null  float64
 35  var_6m_price_off_peak            14606 non-null  float64
 36  var_6m_price_peak                14606 non-null  float64
 37  var_6m_price_mid_peak            14606 non-null  float64
 38  churn                            14606 non-null  int64
dtypes: float64(37), int64(2)
memory usage: 4.5 MB

# Tunning using OPTUNA Library

In [27]:
!pip install optunahub

Collecting optunahub
  Downloading optunahub-0.2.0-py3-none-any.whl.metadata (6.3 kB)
Collecting ga4mp (from optunahub)
  Downloading ga4mp-2.0.4-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: optuna in /usr/local/lib/python3.11/dist-packages (from optunahub) (4.2.1)
Collecting PyGithub>=1.59 (from optunahub)
  Downloading PyGithub-2.6.1-py3-none-any.whl.metadata (3.9 kB)
Collecting pynacl>=1.4.0 (from PyGithub>=1.59->optunahub)
  Downloading PyNaCl-1.5.0-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl.metadata (8.6 kB)
Requirement already satisfied: requests>=2.14.0 in /usr/local/lib/python3.11/dist-packages (from PyGithub>=1.59->optunahub) (2.32.3)
Collecting pyjwt>=2.4.0 (from pyjwt[crypto]>=2.4.0->PyGithub>=1.59->optunahub)
  Downloading PyJWT-2.10.1-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.11/dist-packages (from PyGithub>=1.59->optunahub) (4.12.2)
Requirement already satisfied: urllib3>=1.26.0 in /usr/local/lib/python3.11/dist-packages (from PyGithub>=1.59->optunahub) (2.3.0)
Collecting Deprecated (from PyGithub>=1.59->optunahub)
  Downloading Deprecated-1.2.18-py2.py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.11/dist-packages (from optuna->optunahub) (1.15.2)
Requirement already satisfied: colorlog in /usr/local/lib/python3.11/dist-packages (from optuna->optunahub) (6.9.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from optuna->optunahub) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from optuna->optunahub) (24.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.11/dist-packages (from optuna->optunahub) (2.0.40)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from optuna->optunahub) (4.67.1)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.11/dist-packages (from optuna->optunahub) (6.0.2)
Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic>=1.5.0->optuna->optunahub) (1.1.3)
Requirement already satisfied: cryptography>=3.4.0 in /usr/lib/python3/dist-packages (from pyjwt[crypto]>=2.4.0->PyGithub>=1.59->optunahub) (3.4.8)
Requirement already satisfied: cffi>=1.4.1 in /usr/local/lib/python3.11/dist-packages (from pynacl>=1.4.0->PyGithub>=1.59->optunahub) (1.17.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.14.0->PyGithub>=1.59->optunahub) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.14.0->PyGithub>=1.59->optunahub) (3.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.14.0->PyGithub>=1.59->optunahub) (2025.1.31)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.11/dist-packages (from sqlalchemy>=1.4.2->optuna->optunahub) (3.1.1)
Requirement already satisfied: wrapt<2,>=1.10 in /usr/local/lib/python3.11/dist-packages (from Deprecated->PyGithub>=1.59->optunahub) (1.17.2)
Requirement already satisfied: pycparser in /usr/local/lib/python3.11/dist-packages (from cffi>=1.4.1->pynacl>=1.4.0->PyGithub>=1.59->optunahub) (2.22)
Downloading optunahub-0.2.0-py3-none-any.whl (11 kB)
Downloading PyGithub-2.6.1-py3-none-any.whl (410 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.5/410.5 kB 8.7 MB/s eta 0:00:00
Downloading ga4mp-2.0.4-py3-none-any.whl (15 kB)
Downloading PyJWT-2.10.1-py3-none-any.whl (22 kB)
Downloading PyNaCl-1.5.0-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (856 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 856.7/856.7 kB 29.1 MB/s eta 0:00:00
Downloading Deprecated-1.2.18-py2.py3-none-any.whl (10.0 kB)
Installing collected packages: pyjwt, ga4mp, Deprecated, pynacl, PyGithub, optunahub
  Attempting uninstall: pyjwt
    Found existing installation: PyJWT 2.3.0
    Uninstalling PyJWT-2.3.0:
      Successfully uninstalled PyJWT-2.3.0
Successfully installed Deprecated-1.2.18 PyGithub-2.6.1 ga4mp-2.0.4 optunahub-0.2.0 pyjwt-2.10.1 pynacl-1.5.0

In [28]:
import optunahub

In [29]:
def objective(trial: optuna.Trial):
    classifier_name = trial.suggest_categorical('classifier', ['RandomForest'])
    n_estimators = trial.suggest_int('n_estimators', 50, 1000, step=1)
    max_depth = trial.suggest_int('max_depth', 10, 100, step=1)
    min_samples_split = trial.suggest_int('min_samples_split', 2, 20, step=1)
    min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 20, step=1)
    min_weight_fraction_leaf = trial.suggest_float('min_weight_fraction_leaf', 0.0, 0.5)
    max_features = trial.suggest_categorical('max_features', ['sqrt', 'log2'])
    max_leaf_nodes = trial.suggest_int('max_leaf_nodes', 2, 500, step=1)
    min_impurity_decrease = trial.suggest_float('min_impurity_decrease', 0.0, 0.5)
    bootstrap = trial.suggest_categorical('bootstrap', [True, False])
    oob_score = trial.suggest_categorical('oob_score', [True, False])
    if oob_score and not bootstrap:
        oob_score = False

    if classifier_name == 'RandomForest':
        classifier = RandomForestClassifier(
            n_estimators=n_estimators,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            min_weight_fraction_leaf=min_weight_fraction_leaf,
            max_features=max_features,
            max_leaf_nodes=max_leaf_nodes,
            min_impurity_decrease=min_impurity_decrease,
            bootstrap=bootstrap,
            oob_score=oob_score,
            random_state=42
        )

    # Use cross-validation score
    try:
        score = cross_val_score(classifier, X_train, y_train, cv=3, scoring='accuracy')  # Use a few folds
        return score.mean() # Return the mean of the scores
    except ValueError as e:
        print(f"ValueError in trial: {e}")
        return float('-inf')

# Create an Optuna study and optimize the objective function
module = optunahub.load_module(package="samplers/tpe_tutorial")

# Initialize the CustomizableTPESampler
sampler = module.CustomizableTPESampler()

# Create an Optuna study with the sampler
study = optuna.create_study(direction='maximize', sampler=sampler)
study.optimize(objective, n_trials=133)

# Print the best parameters and the corresponding accuracy
print("Best parameters:", study.best_params)
print("Best accuracy:", study.best_value)

/usr/local/lib/python3.11/dist-packages/optuna/_experimental.py:31: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2025-03-30 10:08:38,753] A new study created in memory with name: no-name-554fd23e-5b00-4719-8bf7-500cd8b0b952
[I 2025-03-30 10:08:46,891] Trial 0 finished with value: 0.9028586159675561 and parameters: {'classifier': 'RandomForest', 'n_estimators': 926, 'max_depth': 41, 'min_samples_split': 7, 'min_samples_leaf': 5, 'min_weight_fraction_leaf': 0.43965035780731215, 'max_features': 'log2', 'max_leaf_nodes': 3, 'min_impurity_decrease': 0.18553144269102417, 'bootstrap': True, 'oob_score': False}. Best is trial 0 with value: 0.9028586159675561.
[I 2025-03-30 10:08:47,957] Trial 1 finished with value: 0.9028586159675561 and parameters: {'classifier': 'RandomForest', 'n_estimators': 114, 'max_depth': 30, 'min_samples_split': 17, 'min_samples_leaf': 9, 'min_weight_fraction_leaf': 0.35015418286106825, 'max_features': 'log2', 'max_leaf_nodes': 67, 'min_impurity_decrease': 0.05280360971810805, 'bootstrap': False, 'oob_score': False}. Best is trial 0 with value: 0.9028586159675561.
[I 2025-03-30 10:08:53,565] Trial 2 finished with value: 0.9028586159675561 and parameters: {'classifier': 'RandomForest', 'n_estimators': 537, 'max_depth': 86, 'min_samples_split': 4, 'min_samples_leaf': 8, 'min_weight_fraction_leaf': 0.12032735123185495, 'max_features': 'sqrt', 'max_leaf_nodes': 34, 'min_impurity_decrease': 0.04508960286136776, 'bootstrap': False, 'oob_score': True}. Best is trial 0 with value: 0.9028586159675561.
[I 2025-03-30 10:08:59,596] Trial 3 finished with value: 0.9028586159675561 and parameters: {'classifier': 'RandomForest', 'n_estimators': 682, 'max_depth': 67, 'min_samples_split': 11, 'min_samples_leaf': 8, 'min_weight_fraction_leaf': 0.2582819091873859, 'max_features': 'log2', 'max_leaf_nodes': 209, 'min_impurity_decrease': 0.02251201027935229, 'bootstrap': True, 'oob_score': False}. Best is trial 0 with value: 0.9028586159675561.
[I 2025-03-30 10:09:07,432] Trial 4 finished with value: 0.9028586159675561 and parameters: {'classifier': 'RandomForest', 'n_estimators': 732, 'max_depth': 80, 'min_samples_split': 12, 'min_samples_leaf': 7, 'min_weight_fraction_leaf': 0.006330171378869431, 'max_features': 'sqrt', 'max_leaf_nodes': 244, 'min_impurity_decrease': 0.08292509954407862, 'bootstrap': False, 'oob_score': True}. Best is trial 0 with value: 0.9028586159675561.
[I 2025-03-30 10:09:15,312] Trial 5 finished with value: 0.9028586159675561 and parameters: {'classifier': 'RandomForest', 'n_estimators': 763, 'max_depth': 35, 'min_samples_split': 7, 'min_samples_leaf': 13, 'min_weight_fraction_leaf': 0.3997801017222108, 'max_features': 'sqrt', 'max_leaf_nodes': 445, 'min_impurity_decrease': 0.23185232718879073, 'bootstrap': False, 'oob_score': False}. Best is trial 0 with value: 0.9028586159675561.
[I 2025-03-30 10:09:23,762] Trial 6 finished with value: 0.9028586159675561 and parameters: {'classifier': 'RandomForest', 'n_estimators': 779, 'max_depth': 84, 'min_samples_split': 4, 'min_samples_leaf': 2, 'min_weight_fraction_leaf': 0.4411768929088264, 'max_features': 'log2', 'max_leaf_nodes': 257, 'min_impurity_decrease': 0.42411650453590055, 'bootstrap': True, 'oob_score': True}. Best is trial 0 with value: 0.9028586159675561.
[I 2025-03-30 10:09:31,951] Trial 7 finished with value: 0.9028586159675561 and parameters: {'classifier': 'RandomForest', 'n_estimators': 865, 'max_depth': 42, 'min_samples_split': 14, 'min_samples_leaf': 1, 'min_weight_fraction_leaf': 0.2243827457292828, 'max_features': 'sqrt', 'max_leaf_nodes': 183, 'min_impurity_decrease': 0.17208966349279986, 'bootstrap': True, 'oob_score': False}. Best is trial 0 with value: 0.9028586159675561.
[I 2025-03-30 10:09:34,368] Trial 8 finished with value: 0.9028586159675561 and parameters: {'classifier': 'RandomForest', 'n_estimators': 215, 'max_depth': 69, 'min_samples_split': 19, 'min_samples_leaf': 1, 'min_weight_fraction_leaf': 0.18533160532436238, 'max_features': 'log2', 'max_leaf_nodes': 215, 'min_impurity_decrease': 0.1381280383013581, 'bootstrap': True, 'oob_score': True}. Best is trial 0 with value: 0.9028586159675561.
[I 2025-03-30 10:09:40,265] Trial 9 finished with value: 0.9028586159675561 and parameters: {'classifier': 'RandomForest', 'n_estimators': 566, 'max_depth': 21, 'min_samples_split': 6, 'min_samples_leaf': 7, 'min_weight_fraction_leaf': 0.09814579947127705, 'max_features': 'sqrt', 'max_leaf_nodes': 396, 'min_impurity_decrease': 0.4934179886342863, 'bootstrap': False, 'oob_score': True}. Best is trial 0 with value: 0.9028586159675561.
[I 2025-03-30 10:09:46,689] Trial 10 finished with value: 0.9028586159675561 and parameters: {'classifier': 'RandomForest', 'n_estimators': 735, 'max_depth': 33, 'min_samples_split': 10, 'min_samples_leaf': 5, 'min_weight_fraction_leaf': 0.3864638872022546, 'max_features': 'log2', 'max_leaf_nodes': 16, 'min_impurity_decrease': 0.2178229504338863, 'bootstrap': True, 'oob_score': False}. Best is trial 0 with value: 0.9028586159675561.
[I 2025-03-30 10:09:52,715] Trial 11 finished with value: 0.9028586159675561 and parameters: {'classifier': 'RandomForest', 'n_estimators': 688, 'max_depth': 42, 'min_samples_split': 2, 'min_samples_leaf': 4, 'min_weight_fraction_leaf': 0.3580422165516537, 'max_features': 'log2', 'max_leaf_nodes': 96, 'min_impurity_decrease': 0.16712036019171903, 'bootstrap': True, 'oob_score': False}. Best is trial 0 with value: 0.9028586159675561.
[I 2025-03-30 10:10:00,965] Trial 12 finished with value: 0.9028586159675561 and parameters: {'classifier': 'RandomForest', 'n_estimators': 942, 'max_depth': 56, 'min_samples_split': 3, 'min_samples_leaf': 2, 'min_weight_fraction_leaf': 0.4838045858275324, 'max_features': 'log2', 'max_leaf_nodes': 29, 'min_impurity_decrease': 0.28868256510619256, 'bootstrap': True, 'oob_score': False}. Best is trial 0 with value: 0.9028586159675561.
[I 2025-03-30 10:10:09,452] Trial 13 finished with value: 0.9028586159675561 and parameters: {'classifier': 'RandomForest', 'n_estimators': 974, 'max_depth': 61, 'min_samples_split': 9, 'min_samples_leaf': 3, 'min_weight_fraction_leaf': 0.47485093922996263, 'max_features': 'log2', 'max_leaf_nodes': 33, 'min_impurity_decrease': 0.07572482233596284, 'bootstrap': True, 'oob_score': False}. Best is trial 0 with value: 0.9028586159675561.
[I 2025-03-30 10:10:13,450] Trial 14 finished with value: 0.9028586159675561 and parameters: {'classifier': 'RandomForest', 'n_estimators': 381, 'max_depth': 90, 'min_samples_split': 5, 'min_samples_leaf': 7, 'min_weight_fraction_leaf': 0.07636397633428013, 'max_features': 'sqrt', 'max_leaf_nodes': 67, 'min_impurity_decrease': 0.0960936498328889, 'bootstrap': False, 'oob_score': True}. Best is trial 0 with value: 0.9028586159675561.
[I 2025-03-30 10:10:20,604] Trial 15 finished with value: 0.9028586159675561 and parameters: {'classifier': 'RandomForest', 'n_estimators': 818, 'max_depth': 29, 'min_samples_split': 3, 'min_samples_leaf': 10, 'min_weight_fraction_leaf': 0.4397239305544544, 'max_features': 'log2', 'max_leaf_nodes': 25, 'min_impurity_decrease': 0.09918828280904522, 'bootstrap': True, 'oob_score': False}. Best is trial 0 with value: 0.9028586159675561.
[I 2025-03-30 10:10:23,044] Trial 16 finished with value: 0.9028586159675561 and parameters: {'classifier': 'RandomForest', 'n_estimators': 261, 'max_depth': 27, 'min_samples_split': 16, 'min_samples_leaf': 10, 'min_weight_fraction_leaf': 0.2700976455743624, 'max_features': 'log2', 'max_leaf_nodes': 105, 'min_impurity_decrease': 0.04045708415301968, 'bootstrap': False, 'oob_score': False}. Best is trial 0 with value: 0.9028586159675561.
[I 2025-03-30 10:10:27,660] Trial 17 finished with value: 0.9028586159675561 and parameters: {'classifier': 'RandomForest', 'n_estimators': 440, 'max_depth': 77, 'min_samples_split': 5, 'min_samples_leaf': 5, 'min_weight_fraction_leaf': 0.08965535990447795, 'max_features': 'sqrt', 'max_leaf_nodes': 52, 'min_impurity_decrease': 0.024489133960150282, 'bootstrap': False, 'oob_score': True}. Best is trial 0 with value: 0.9028586159675561.
[I 2025-03-30 10:10:36,274] Trial 18 finished with value: 0.9028586159675561 and parameters: {'classifier': 'RandomForest', 'n_estimators': 810, 'max_depth': 54, 'min_samples_split': 6, 'min_samples_leaf': 6, 'min_weight_fraction_leaf': 0.098991910744288, 'max_features': 'sqrt', 'max_leaf_nodes': 32, 'min_impurity_decrease': 0.010069079461277455, 'bootstrap': False, 'oob_score': True}. Best is trial 0 with value: 0.9028586159675561.
[I 2025-03-30 10:10:43,725] Trial 19 finished with value: 0.9028586159675561 and parameters: {'classifier': 'RandomForest', 'n_estimators': 846, 'max_depth': 31, 'min_samples_split': 5, 'min_samples_leaf': 1, 'min_weight_fraction_leaf': 0.4315391429500673, 'max_features': 'log2', 'max_leaf_nodes': 2, 'min_impurity_decrease': 0.1865399559693114, 'bootstrap': True, 'oob_score': False}. Best is trial 0 with value: 0.9028586159675561.
[I 2025-03-30 10:10:50,373] Trial 20 finished with value: 0.9028586159675561 and parameters: {'classifier': 'RandomForest', 'n_estimators': 763, 'max_depth': 51, 'min_samples_split': 8, 'min_samples_leaf': 4, 'min_weight_fraction_leaf': 0.39985309720420587, 'max_features': 'log2', 'max_leaf_nodes': 10, 'min_impurity_decrease': 0.12458745321087225, 'bootstrap': True, 'oob_score': False}. Best is trial 0 with value: 0.9028586159675561.
[I 2025-03-30 10:10:55,324] Trial 21 finished with value: 0.9028586159675561 and parameters: {'classifier': 'RandomForest', 'n_estimators': 468, 'max_depth': 84, 'min_samples_split': 3, 'min_samples_leaf': 9, 'min_weight_fraction_leaf': 0.13808604382840184, 'max_features': 'sqrt', 'max_leaf_nodes': 48, 'min_impurity_decrease': 0.05256213121276938, 'bootstrap': False, 'oob_score': True}. Best is trial 0 with value: 0.9028586159675561.
[I 2025-03-30 10:11:04,431] Trial 22 finished with value: 0.9028586159675561 and parameters: {'classifier': 'RandomForest', 'n_estimators': 963, 'max_depth': 42, 'min_samples_split': 6, 'min_samples_leaf': 6, 'min_weight_fraction_leaf': 0.374216711424302, 'max_features': 'sqrt', 'max_leaf_nodes': 32, 'min_impurity_decrease': 0.24652405140363898, 'bootstrap': True, 'oob_score': False}. Best is trial 0 with value: 0.9028586159675561.
[I 2025-03-30 10:11:10,326] Trial 23 finished with value: 0.9028586159675561 and parameters: {'classifier': 'RandomForest', 'n_estimators': 561, 'max_depth': 81, 'min_samples_split': 8, 'min_samples_leaf': 7, 'min_weight_fraction_leaf': 0.2169993032053636, 'max_features': 'sqrt', 'max_leaf_nodes': 28, 'min_impurity_decrease': 0.014153567032567274, 'bootstrap': False, 'oob_score': True}. Best is trial 0 with value: 0.9028586159675561.
[I 2025-03-30 10:11:16,104] Trial 24 finished with value: 0.9028586159675561 and parameters: {'classifier': 'RandomForest', 'n_estimators': 659, 'max_depth': 27, 'min_samples_split': 4, 'min_samples_leaf': 7, 'min_weight_fraction_leaf': 0.3701393687314241, 'max_features': 'log2', 'max_leaf_nodes': 4, 'min_impurity_decrease': 0.22678749746984672, 'bootstrap': True, 'oob_score': False}. Best is trial 0 with value: 0.9028586159675561.
[I 2025-03-30 10:11:23,570] Trial 25 finished with value: 0.9028586159675561 and parameters: {'classifier': 'RandomForest', 'n_estimators': 851, 'max_depth': 33, 'min_samples_split': 10, 'min_samples_leaf': 5, 'min_weight_fraction_leaf': 0.4761571496244758, 'max_features': 'log2', 'max_leaf_nodes': 17, 'min_impurity_decrease': 0.22019460825077386, 'bootstrap': True, 'oob_score': False}. Best is trial 0 with value: 0.9028586159675561.
[I 2025-03-30 10:11:29,522] Trial 26 finished with value: 0.9028586159675561 and parameters: {'classifier': 'RandomForest', 'n_estimators': 670, 'max_depth': 66, 'min_samples_split': 9, 'min_samples_leaf': 8, 'min_weight_fraction_leaf': 0.2038502722167967, 'max_features': 'log2', 'max_leaf_nodes': 265, 'min_impurity_decrease': 0.02731769776953764, 'bootstrap': True, 'oob_score': False}. Best is trial 0 with value: 0.9028586159675561.
[I 2025-03-30 10:11:36,212] Trial 27 finished with value: 0.9028586159675561 and parameters: {'classifier': 'RandomForest', 'n_estimators': 633, 'max_depth': 63, 'min_samples_split': 7, 'min_samples_leaf': 9, 'min_weight_fraction_leaf': 0.14546267480906744, 'max_features': 'sqrt', 'max_leaf_nodes': 45, 'min_impurity_decrease': 0.04169178734670379, 'bootstrap': False, 'oob_score': True}. Best is trial 0 with value: 0.9028586159675561.
[I 2025-03-30 10:11:43,647] Trial 28 finished with value: 0.9028586159675561 and parameters: {'classifier': 'RandomForest', 'n_estimators': 713, 'max_depth': 87, 'min_samples_split': 5, 'min_samples_leaf': 8, 'min_weight_fraction_leaf': 0.39288269560506744, 'max_features': 'sqrt', 'max_leaf_nodes': 21, 'min_impurity_decrease': 0.05902488538406934, 'bootstrap': False, 'oob_score': True}. Best is trial 0 with value: 0.9028586159675561.
[I 2025-03-30 10:11:51,622] Trial 29 finished with value: 0.9028586159675561 and parameters: {'classifier': 'RandomForest', 'n_estimators': 754, 'max_depth': 83, 'min_samples_split': 8, 'min_samples_leaf': 7, 'min_weight_fraction_leaf': 0.1242618582820993, 'max_features': 'sqrt', 'max_leaf_nodes': 252, 'min_impurity_decrease': 0.010861119122251114, 'bootstrap': False, 'oob_score': True}. Best is trial 0 with value: 0.9028586159675561.
[I 2025-03-30 10:11:59,647] Trial 30 finished with value: 0.9028586159675561 and parameters: {'classifier': 'RandomForest', 'n_estimators': 923, 'max_depth': 61, 'min_samples_split': 10, 'min_samples_leaf': 6, 'min_weight_fraction_leaf': 0.4943602445310246, 'max_features': 'log2', 'max_leaf_nodes': 17, 'min_impurity_decrease': 0.21336234058133297, 'bootstrap': True, 'oob_score': False}. Best is trial 0 with value: 0.9028586159675561.
[I 2025-03-30 10:12:05,140] Trial 31 finished with value: 0.9028586159675561 and parameters: {'classifier': 'RandomForest', 'n_estimators': 620, 'max_depth': 68, 'min_samples_split': 13, 'min_samples_leaf': 7, 'min_weight_fraction_leaf': 0.28511087727621587, 'max_features': 'log2', 'max_leaf_nodes': 139, 'min_impurity_decrease': 0.029591792120299974, 'bootstrap': True, 'oob_score': False}. Best is trial 0 with value: 0.9028586159675561.
[I 2025-03-30 10:12:12,659] Trial 32 finished with value: 0.9028586159675561 and parameters: {'classifier': 'RandomForest', 'n_estimators': 709, 'max_depth': 75, 'min_samples_split': 11, 'min_samples_leaf': 5, 'min_weight_fraction_leaf': 0.02908815035416193, 'max_features': 'sqrt', 'max_leaf_nodes': 232, 'min_impurity_decrease': 0.1223193123650471, 'bootstrap': False, 'oob_score': True}. Best is trial 0 with value: 0.9028586159675561.
[I 2025-03-30 10:12:21,165] Trial 33 finished with value: 0.9028586159675561 and parameters: {'classifier': 'RandomForest', 'n_estimators': 966, 'max_depth': 51, 'min_samples_split': 8, 'min_samples_leaf': 5, 'min_weight_fraction_leaf': 0.37603456173499855, 'max_features': 'log2', 'max_leaf_nodes': 29, 'min_impurity_decrease': 0.17334485624573598, 'bootstrap': True, 'oob_score': False}. Best is trial 0 with value: 0.9028586159675561.
[I 2025-03-30 10:12:26,571] Trial 34 finished with value: 0.9028586159675561 and parameters: {'classifier': 'RandomForest', 'n_estimators': 515, 'max_depth': 87, 'min_samples_split': 10, 'min_samples_leaf': 9, 'min_weight_fraction_leaf': 0.16610587379100775, 'max_features': 'sqrt', 'max_leaf_nodes': 28, 'min_impurity_decrease': 0.0793974773540399, 'bootstrap': False, 'oob_score': True}. Best is trial 0 with value: 0.9028586159675561.
[I 2025-03-30 10:12:32,581] Trial 35 finished with value: 0.9028586159675561 and parameters: {'classifier': 'RandomForest', 'n_estimators': 580, 'max_depth': 99, 'min_samples_split': 3, 'min_samples_leaf': 9, 'min_weight_fraction_leaf': 0.239547033278746, 'max_features': 'sqrt', 'max_leaf_nodes': 57, 'min_impurity_decrease': 0.04669200495627483, 'bootstrap': False, 'oob_score': True}. Best is trial 0 with value: 0.9028586159675561.
[I 2025-03-30 10:12:37,804] Trial 36 finished with value: 0.9028586159675561 and parameters: {'classifier': 'RandomForest', 'n_estimators': 491, 'max_depth': 92, 'min_samples_split': 2, 'min_samples_leaf': 9, 'min_weight_fraction_leaf': 0.006196624541412982, 'max_features': 'sqrt', 'max_leaf_nodes': 25, 'min_impurity_decrease': 0.07978509991480381, 'bootstrap': False, 'oob_score': True}. Best is trial 0 with value: 0.9028586159675561.
[I 2025-03-30 10:12:45,958] Trial 37 finished with value: 0.9028586159675561 and parameters: {'classifier': 'RandomForest', 'n_estimators': 935, 'max_depth': 54, 'min_samples_split': 7, 'min_samples_leaf': 1, 'min_weight_fraction_leaf': 0.40970396338911064, 'max_features': 'log2', 'max_leaf_nodes': 31, 'min_impurity_decrease': 0.19203065906596337, 'bootstrap': True, 'oob_score': False}. Best is trial 0 with value: 0.9028586159675561.
[I 2025-03-30 10:12:53,720] Trial 38 finished with value: 0.9028586159675561 and parameters: {'classifier': 'RandomForest', 'n_estimators': 728, 'max_depth': 71, 'min_samples_split': 17, 'min_samples_leaf': 8, 'min_weight_fraction_leaf': 0.003825245602335207, 'max_features': 'sqrt', 'max_leaf_nodes': 270, 'min_impurity_decrease': 0.05609073810245849, 'bootstrap': False, 'oob_score': True}. Best is trial 0 with value: 0.9028586159675561.
[I 2025-03-30 10:13:00,625] Trial 39 finished with value: 0.9028586159675561 and parameters: {'classifier': 'RandomForest', 'n_estimators': 785, 'max_depth': 74, 'min_samples_split': 12, 'min_samples_leaf': 7, 'min_weight_fraction_leaf': 0.22879092077949306, 'max_features': 'log2', 'max_leaf_nodes': 313, 'min_impurity_decrease': 0.03729188627491396, 'bootstrap': True, 'oob_score': False}. Best is trial 0 with value: 0.9028586159675561.
[I 2025-03-30 10:13:08,364] Trial 40 finished with value: 0.9028586159675561 and parameters: {'classifier': 'RandomForest', 'n_estimators': 889, 'max_depth': 37, 'min_samples_split': 5, 'min_samples_leaf': 9, 'min_weight_fraction_leaf': 0.47064212426099505, 'max_features': 'log2', 'max_leaf_nodes': 6, 'min_impurity_decrease': 0.19070756459267516, 'bootstrap': True, 'oob_score': False}. Best is trial 0 with value: 0.9028586159675561.
[I 2025-03-30 10:13:16,166] Trial 41 finished with value: 0.9028586159675561 and parameters: {'classifier': 'RandomForest', 'n_estimators': 750, 'max_depth': 33, 'min_samples_split': 6, 'min_samples_leaf': 7, 'min_weight_fraction_leaf': 0.4145618634439335, 'max_features': 'sqrt', 'max_leaf_nodes': 449, 'min_impurity_decrease': 0.19949771994749066, 'bootstrap': False, 'oob_score': False}. Best is trial 0 with value: 0.9028586159675561.
[I 2025-03-30 10:13:23,914] Trial 42 finished with value: 0.9028586159675561 and parameters: {'classifier': 'RandomForest', 'n_estimators': 749, 'max_depth': 37, 'min_samples_split': 7, 'min_samples_leaf': 15, 'min_weight_fraction_leaf': 0.4145366794034507, 'max_features': 'sqrt', 'max_leaf_nodes': 392, 'min_impurity_decrease': 0.2746931701275124, 'bootstrap': False, 'oob_score': False}. Best is trial 0 with value: 0.9028586159675561.
[I 2025-03-30 10:13:31,168] Trial 43 finished with value: 0.9028586159675561 and parameters: {'classifier': 'RandomForest', 'n_estimators': 678, 'max_depth': 74, 'min_samples_split': 3, 'min_samples_leaf': 8, 'min_weight_fraction_leaf': 0.05501162470173929, 'max_features': 'sqrt', 'max_leaf_nodes': 75, 'min_impurity_decrease': 0.047609715591471306, 'bootstrap': False, 'oob_score': True}. Best is trial 0 with value: 0.9028586159675561.

Best parameters: {'classifier': 'RandomForest', 'n_estimators': 926, 'max_depth': 41, 'min_samples_split': 7, 'min_samples_leaf': 5, 'min_weight_fraction_leaf': 0.43965035780731215, 'max_features': 'log2', 'max_leaf_nodes': 3, 'min_impurity_decrease': 0.18553144269102417, 'bootstrap': True, 'oob_score': False}
Best accuracy: 0.9028586159675561

In [30]:
print("Best parameters:", study.best_params)
print("Best accuracy:", study.best_value)

Best parameters: {'classifier': 'RandomForest', 'n_estimators': 926, 'max_depth': 41, 'min_samples_split': 7, 'min_samples_leaf': 5, 'min_weight_fraction_leaf': 0.43965035780731215, 'max_features': 'log2', 'max_leaf_nodes': 3, 'min_impurity_decrease': 0.18553144269102417, 'bootstrap': True, 'oob_score': False}
Best accuracy: 0.9028586159675561

In [32]:
np.set_printoptions(precision=3)

In [37]:
classifer = RandomForestClassifier(n_estimators=926, max_depth=41,min_samples_split=7,
                                   min_samples_leaf=5, min_weight_fraction_leaf=0.43965035780731215, max_features="log2",
                                   max_leaf_nodes=3, min_impurity_decrease=0.18553144269102417, bootstrap=True, oob_score=False
                                   ).fit(X_train, y_train)

In [38]:
y_pred = classifer.predict(X_test)

In [39]:
accuracy_score(y_test, y_pred)

0.9028062970568104

In [42]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.90      1.00      0.95      2638
           1       0.00      0.00      0.00       284

    accuracy                           0.90      2922
   macro avg       0.45      0.50      0.47      2922
weighted avg       0.82      0.90      0.86      2922

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [41]:
jaccard_score(y_test, y_pred, pos_label=0)

np.float64(0.9028062970568104)